
# Preparation

Our primary computing context will be the [UC Berkeley DataHub](../prep.qmd). This provides us with a common platform on which we are assured to get the same behavior as each other, allowing us to use the command line/shell/terminal and Python, including Jupyter notebooks. In particular getting a common command line environment would be hard otherwise. 

::: {.callout-note collapse="true"}
## Using your own laptop (optional)

If you haven't already used the shell/terminal and Python on your laptop, we recommend you use the DataHub so that we don't have to troubleshoot problems on multiple laptops.

If you do use your laptop, you'll need Python installed, for which we recommend using [Miniforge](https://github.com/conda-forge/miniforge). Another option is the Anaconda distribution of Python](https://www.anaconda.com/distribution)

For the shell/terminal parts of this material, you can use the Terminal on your Mac, but not on Windows.

If you do use your own laptop, you'll need to *clone* [this GitHub repository](https://github.com/berkeley-scf/compute-skills-2024). If you don't know how to do that, just download [this zip file](https://github.com/berkeley-scf/compute-skills-2024/archive/refs/heads/main.zip) and unzip it into your home directory on your computer.
:::
